### ISSUE TITLE
'this' not working on certain cases on versions >= 1.0.0

### ISSUE THREAD

**Issue by Pferv** [TheBrainFamily/cypress-cucumber-preprocessor#101]
I've been using this library for quite a while now and I'm stuck in the 0.6.0 version ever since, there is no real problem about that, It woks perfectly, but seeing the 'this' topic come up in #96 made me think that it might be worth showing my problems with the new versions just in case they are fixable.

I've tested the 1.5.1 version(I already tried most versions from 1.0.0 on) and saw that 'this' works but only if your step definitions are written as classic functions, it doesn't work if they are written as arrow functions. 

I've also noticed that starting on version 1.0.0 it no longer waits for a step to finish before moving to the next one, so if you set a value inside a then block you won't be able to access it in your next steps. This part is a bit difficult to explain for me, but I have a small example that shows the 3 cases and hopefully will be easier to understand:

```cucumber
Feature: this test
  Scenario: this test with classic function
    When I fill a simple var
    Then The first variable contains the right value

  Scenario: this test with arrow function
    When I fill a simple var in an arrow function
    Then The second variable contains the right value

  Scenario: variable filled inside then block
    When I fill a variable inside a then block
    Then The third variable contains the right value
```

```javascript
when("I fill a simple var", function() {
  this.var1 = "var1";
});

when("I fill a simple var in an arrow function", () => {
  this.var2 = "var2";
});

when("I fill a variable inside a then block", function() {
  cy.visit("https://github.com");
  cy.get("h1.text-white.lh-condensed-ultra")
    .invoke("text")
    .then(text1 => {
      this.var3 = text1;
      console.log(`then block var3: ${this.var3}`);
    });
});

then("The first variable contains the right value", function() {
  console.log(`var1: ${this.var1}`);
  expect("var1").to.equal(this.var1);
});

then("The second variable contains the right value", () => {
  console.log(`var2: ${this.var2}`);
  expect("var2").to.equal(this.var2);
});

then("The third variable contains the right value", function() {
  console.log(`var3: ${this.var3}`);
  expect("Built for developers").to.equal(this.var3);
});
```

This 3 tests work on 0.6.0, but only the first one works on 1.5.1. 

I'm aware that the third test problem in 1.x.x versions might be quite coupled with the 1.0.0 update which made scenarios run as single steps and I'm not really sure if it can be fixed until that change can be undone(not before this happens https://github.com/cypress-io/cypress/issues/686 I assume) but I think it's interesting to discuss it at least.

Thank you!

**Comment by lgandecki** [comment]
Yes, you have to use functions, mocha - that is used by cypress underneath - doesn't like arrow functions ( https://mochajs.org/#arrow-functions )

As for .then(), interesting case. that wouldn't work inside a cypress test as well. It worked accidentally before, because it would wait for all the queues cypress actions to finish before moving to another test. But, as you noticed here, it's all in one tests now, it doesn't wait, so the functions are first queued, and then executed. If you try to do any expectations in between the queueing, things won't be ready yet.

try

```javascript
then("The third variable contains the right value", function() {
  cy.then(() => {
    console.log(`var3: ${this.var3}`);
    expect("Built for developers").to.equal(this.var3);
  })
});
```

**Comment by mattgibson** [comment]
It would be great to have a way to pass variables without using `this`. The examples in the docs only refer to routes and DOM elements. If I want to take data from one page and check it exists on another page, there is no easy way to do it.

```
cy.setVar('a string`).as('myVariable');
expect(cy.get('pageElement').text()).toEqual(cy.getVar('myVariable'));
```

**Comment by lgandecki** [comment]
@mattgibson I think here you would have to cy.then() as shown above. Otherwise the expect will run before the variables are properly resolved. This will be the same no matter if you use this package or pure cypress directly. Think about it as if the cy.get(').text() was a promise that you didn't wait for - you would be comparing a promise with a text
