### ISSUE TITLE
Run/watch a single scenario

### ISSUE THREAD

**Issue by hackel** [TheBrainFamily/cypress-cucumber-preprocessor#111]
If I open a feature file in Cypress, whenever I make a change to a step definition, every single scenario gets run again.  Is there any way to prevent this and only run the scenarios that have actually been modified?  Even if it was a button to manually trigger a re-test of that scenario instead of the entire feature file, that would be better than nothing.  Would temporarily tagging a specific scenario as "current" or something be the best way to achieve this currently?

Somewhat related, is there a way to run just a single scenario, e.g. by specifying the line number on the command line?  It looks like Cypress doesn't even support this natively in spec files yet, but it is rather essential during development.

**Comment by lgandecki** [comment]
I've made contributions to webdriverio, webdriverio-cucumber implementation, cucumberjs itself, chimpjs that uses cucumber for acceptance testing, and tried many more cucumber-related tools. I've never seen such an extensive watch mode at least in the JS world. Could you show me an example where magic like that happens? 

I don't have anything against this idea, and would be happy to have this functionality, but this is a tiny and very new project, comparing to some of the giants :) And since this is really a wrapper around mocha it makes it even more difficult comparing to solutions that are pure cucumberjs.

But yeah, for now you could use tags. :)

**Comment by hackel** [comment]
Yeah, fair enough, I didn't mean to suggest the creation of a new magic watch framework capable of that level of code analysis.  Basically just looking for the equivalent of mocha's `it.only`.  In the meantime, I've been using tags and that gets the job done, but involves a lot of stopping and starting my test environment.  That could be avoided if there was a way to only filter by the `@only` tag when it is present in the feature file, otherwise run everything like normal.

**Comment by lgandecki** [comment]
Hmmm... I see.. how about you just put @only at the top of the feature level while running cypress with @only tag? Is this very inconvenient?

**Comment by hackel** [comment]
Yes, that would get the job done!  I'll stick with that for now and see how it goes.  Thanks.

**Comment by lgandecki** [comment]
I've been toying with an idea of @focus tag (similar to what we have in [chimpy](http://github.com/TheBrainFamily/chimpy) ) , that will allow you to focus on a specific scenario. You wouldn't have to start cypress test with this tag selected for it to work. If we find @focus in a .feature file - we focus. If we don't, we work in a "no-tag" mode, so we run everything. 
Does this make sense?

**Comment by lgandecki** [comment]
@hackel take a look at this PR - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/122/files#diff-04c6e90faac2675aa89e2176d2eec7d8R230  , I think you will like it :-)

**Comment by kayvanbree** [comment]
@hackel @lgandecki this one can be closed I guess.
