### ISSUE TITLE
It is not possible to use regular expressions for step definitions

### ISSUE THREAD

**Issue by maoberlehner** [TheBrainFamily/cypress-cucumber-preprocessor#15]
I'm used to [nightwatch-cucumber](http://mucsi96.github.io/nightwatch-cucumber/) which uses regular expressions by default. It would be very, very useful to have the same possibilities with this package.

Thank you, for working on this package.

**Comment by lgandecki** [comment]
Thanks @maoberlehner !

We are using part of cucumber which is cucumber-expression to resolve the expressions.

I think it should work, but maybe the syntax is a bit different. 

Could you give it a try following these docs: (we will add them to the readme btw, so that's more clear where to look)

https://github.com/cucumber/cucumber/tree/master/cucumber-expressions#regular-expressions-regular-expressions

and if it doesn't work it would be great if you could create a simple reproduction repo so we can jump in and fix this.

Thanks!

**Comment by maoberlehner** [comment]
Ohhh, yeah I've used /^stuff (.*)$/ my fault. Thanks for the quick response!

**Comment by stevepkuo** [comment]
Hi, could you give an example of how you successfully used regular expression within a step definition? I think I had similar issues at (https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/42).
Thanks

**Comment by lgandecki** [comment]
I tried a few things after your post, and I'm not sure if it works.. or if it ever worked actually. The {int} etc works, but regexps seem to be lost. Another thing I wanted to try is to test on a version around this time - since it seemed it might have worked by then :)

**Comment by maoberlehner** [comment]
Hey @stevepkuo and @lgandecki I have to admit, when I wrote the answer I didn't check if Regex actually did work, because I've already moved on with my project and just assumed I did something wrong. I see this was fixed (https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/42#issuecomment-383292357).

Sorry for causing confusion!
