### ISSUE TITLE
Mocha hooks do not work as expected in 1.14.0

### ISSUE THREAD

**Issue by DanAtSpark** [TheBrainFamily/cypress-cucumber-preprocessor#214]
After the release of 1.14.0 version global before and beforeEach hooks do not work as expected.
Global before hook is being run inside each test and beforeEach hook is being run before each test as much times as there are feature files in project.
To reproduce this issue I've created a small [project](https://github.com/DanAtSpark/cypress-cucumber-preprocessor-bug-reproduction).    
## Steps to reproduce
* git clone project
* npm install
* npm run run
* run all specs
Tests won't have any before hook and there will be 2 beforeEach hooks in output

**Comment by lgandecki** [comment]
Shoot. Alright, thanks, I will take a look and either revert or fix. @visusnet would you like to take a look as well, maybe?

**Comment by lgandecki** [comment]
hmm, does it work properly in v1.14.0 ? Or did you went straight for 1.14.1 ?

**Comment by DanAtSpark** [comment]
@lgandecki I cannot run it right now because of `missing step implementation` in 1.4.0
However, I assume that it didn't work properly as I've experienced problems with git hooks about two hours ago.

**Comment by lgandecki** [comment]
I verified 1.14.0 and it's the same problem. 
Btw, are you sure you are talking about 1.4.0 and 1.4.1? IN your repro you used 1.14.1 which is the current version

**Comment by DanAtSpark** [comment]
> 
> 
> I verified 1.14.0 and it's the same problem.
> Btw, are you sure you are talking about 1.4.0 and 1.4.1? IN your repro you used 1.14.1 which is the current version

Sorry, this i mistyped

**Comment by lgandecki** [comment]
Actually, I think this never worked properly and is a reflection of bug in cypress. :(
 https://github.com/cypress-io/cypress/issues/3323

If you run the tests separately, or through  npx cypress run everything should be fine. Could you please verify that on your side in ui-testing-template-cypress ?
I will try to make it work with open nonetheless, but that info would be great to have meanwhile.j

**Comment by DanAtSpark** [comment]
Okay, I will look into running tests through `npx` and update the description.    
However, `before` hooks really work on 1.13 and do not work when I update to 1.14

**Comment by lgandecki** [comment]
It's not about npx, you could do the same with ./node_modules/.bin/cypress run ,  :) when you use the 'run' command tests are run in isolation. But you are right, Before is broken, it runs after beforeEach, and before every test (so basically behaves like beforeEach):

<img width="530" alt="Screen Shot 2019-08-22 at 6 19 18 PM" src="https://user-images.githubusercontent.com/4002543/63522463-72a05b00-c509-11e9-9bb4-a657fe9c0ebf.png">


instead of :


<img width="528" alt="Screen Shot 2019-08-22 at 6 17 45 PM" src="https://user-images.githubusercontent.com/4002543/63522333-2e14bf80-c509-11e9-94c4-6d5bc183530b.png">

**Comment by DanAtSpark** [comment]
Sure, thanks for the explanation, I just haven't used npx.
Actually, the problem with before each hook doesn't lead to an error. However, before hook not being run in time does. Thanks a lot for your quick responses.

**Comment by jcundill** [comment]
Seems that the cucumber '**B**efore' hook is clobbering the mocha '**b**efore'. I guess this is a result of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/c321a171512c31700a9e856e21507955053a6cbe/lib/loader.js#L17

I tried exporting the Before hook capitalised instead of lowercased here https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/c321a171512c31700a9e856e21507955053a6cbe/lib/resolveStepDefinition.js#L203

and then removing the clobbering of the mocha hook in the loader line highlighted above. This results in a more expected behaviour as cypress then still recognises the mocha before hook as something that it needs to run before the actual test starts.

Interestingly, however, pre 1.14.0 with `npx cypress open` and `run all tests` it is even more of a problem as alluded to above.

<img width="536" alt="Screenshot 2019-08-22 at 21 45 29" src="https://user-images.githubusercontent.com/49795386/63549028-7fcc4280-c527-11e9-8663-d0e1228af523.png">

**Comment by jcundill** [comment]
😄 I would go with explicit require - take them off the window.
Then if folks want to use both before and Before they can alias the cucumber hooks themselves in the require if they find it confusing to have both

const { Before: cukeBefore, After: cukeAfter} = require('cypress-cucumber-preprocesser/steps');

**Comment by lgandecki** [comment]
alright, let's do that! Would you want to add a few words to the README.md as well to document all this?

**Comment by sagorla** [comment]
@lgandecki @jcundill 

Cypress events also not working with version 1.14.0 and later.

https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events

Cypress.on('test:after:run', () => {
      cy.log("test")
});
this event will be executed after the test and all afterEach and after hooks run.

And also I have noticed in 1.14.0 and above versions, cucumber JSON generation is happening after "After Hook" execution. In version 1.13.0 & 1.13.1 JSON file is getting generated as soon as feature scenario execution is completed.

**Comment by jcundill** [comment]
@sagorla I think we should run the cucumber JSON generation after the cucumber After hooks - this is what cucumber-js does.  We should actually include the run Before and After hooks into the generated JSON file - this, however, has not been done yet.

I added some logging and see "test:before:run" and "test:after:run" getting called around each test. Can you maybe put together a small repo on github illustrating the problems you are seeing and I'll take a look

**Comment by lgandecki** [comment]
@sagorla could you please create a separate issue, as I think this one is fixed?
