### ISSUE TITLE
Given, When, Then keywords explicitly mapped

### ISSUE THREAD

**Issue by imageica** [TheBrainFamily/cypress-cucumber-preprocessor#28]
Given, When, Then keywords are explicitly mapped, the basic cucumber rules are not getting followed. i.e we are allowed to create duplicate step with a different keyword. For instance given(`user navigates to {string}`) is valid as well as then(`user navigates to {string}`) is also valid. 
I believe the vice versa should be the case, wherein cucumber should allow the use of any keyword to define in the feature file but only one declaration of the step.

**Comment by lgandecki** [comment]
is there cucumber specification about this?

Please correct me if I'm wrong - Are you saying that if I declare it with given in step_definitions I should be able to use it as When in .feature file?

**Comment by imageica** [comment]
@lgandecki  yes that is exactly what i am saying. 
[cucumber wiki](https://github.com/cucumber/cucumber/wiki/Feature-Introduction) states that, "**Every scenario consists of a list of steps, which must start with one of the keywords Given, When, Then, But or And. Cucumber treats them all the same, but you shouldn’t.**" The reason cucumber treats them all same is to restrict step duplication and I think we should too.

**Comment by lgandecki** [comment]
Makes sense. @imageica would you want to give this a try and send a PR? It should be easy to write a failing test (define a step as given in .js file but use it as When in .feature file), I'm happy to review and help if you need some pointers to start with :) 
I do want this package to be driven by the community. The codebase is so small and so well tested that it should be a nice adventure to add features here.
If not - I will take a look but can't promise when, especially since this is a non-blocking issue.

**Comment by imageica** [comment]
@lgandecki I would definitely like to contribute to getting this issue resolved. Can you give me some pointers or some starting point?

**Comment by lgandecki** [comment]
This is fixed in 0.4.0 , please give it a try, and if still doesn't work as needed please create a new issue. 
Thanks for reporting!
