### ISSUE TITLE
Rerun failed scenario

### ISSUE THREAD

**Issue by vinod236** [TheBrainFamily/cypress-cucumber-preprocessor#294]
It looks cypress-cucumber-preprocessor does not support --format option of cucumberjs,  are we getting this feature.

**Comment by jcundill** [comment]
The cucumber js -- format option allows different types of output to be specified - https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats

Cypress already supports all mocha reporters out of the box - https://docs.cypress.io/guides/tooling/reporters.html#Custom-reporter

So we pretty much already have this capability.

@vinod236 I don't completely understand how this relates to rerunning failed scenarios - can you explain in more detail?

Closing for now - please re-open if I've misunderstood the issue here

**Comment by vinod236** [comment]
Hi Jon,
Sorry if for not bieng clear about my question, i was looking for rerun feature for cucumberjs so that when ever i get my scenario/test fails it should be automatically rerun , for that i came across feature in cucumberJS i.e --format rerun:@rerun.txt ,   if we have that feature here Please redirect me to place/page where i can find information about the same.
thanks
Vinod

**Comment by Talank** [comment]
Let us assume there are 5 scenarios in a feature file. While running all the tests, 2 scenarios fails, which were expected to pass. Now a better way to make it pass in CI is to run only those 2 failed scenarios again. Cypress automatically tries to run the failed line, but reruning only one line does not guarantee that the scenario will pass. We want to run all the steps on those 2 scenarios.
Now is there a way to do this with cypress-cucumber-preprocessor? @jcundill 
I think @vinod236 wants to ask the same question here :thinking:

**Comment by far11ven** [comment]
@jcundill any update on this, basically we want to retrigger the failed cucumber tests only

**Comment by surbina** [comment]
Have you tried: https://docs.cypress.io/guides/guides/test-retries#Configure-retry-attempts-for-all-modes ?

**Comment by far11ven** [comment]
@surbina yes, its the self retry mechanism by cypress, but what this thread is about Cucumber's retry or re-execute failed tests only mechanism
