### ISSUE TITLE
Upgrade dependency to Cypress 6.x

### ISSUE THREAD

**Issue by spaque99** [TheBrainFamily/cypress-cucumber-preprocessor#548]
Since Cypress has first released its 6.x version back in Nov 2020, this lib has not upgraded its dependency. 

Is it compatible with version 6.x? Are there any reasons why this has not been upgraded?

Would be great if the main documentation was explicit about the compatibility with dependencies, especially on Cypress.

### Current behavior

The latest version of this lib has a dependency on Cypress 5.x

### Desired behavior

Would like to have it support version 6.x

**Comment by lgandecki** [comment]
That's very curious, why would you make an issue just in case without either trying it or making sure that what you say is actually correct.

Our package does not have a run-time dependency on cypress 5, we only have cypress devDependency set at 5, and that does not matter for what happens when you actually use the package. What it means is that and only that WE USE CYPRESS@5 FOR TESTING OUR PACKAGE. :)  For all intended purposes, whenever you see ANY npm package, you should only be concerned about dependencies and peerDependencies.

**Comment by spaque99** [comment]
Thanks for clarifying. My main intent was to give us assurance that onboarding this lib with Cypress 6.x would work fine. While I understand this is only for testing, there is no information telling us this is compatible. 

Any intention to test on latest version or making the compatibility explicit in the readme? 

I would like to onboard this library and there are concerns in our team that using this lib might create a constraint on upgrading Cypress itself.

**Comment by badeball** [comment]
Open source just means that the code is publically available. It doesn't at all come with assurances or guarantees. This isn't a service promised to you in any way.

**Comment by lgandecki** [comment]
almost 10% of people that use cypress also use our preprocessor. :) This is as much as assurance anyone can give you. Cypress 6 should work fine, since we don't have dependency on cypress itself it should not matter that much what version do you use. There are sometimes breaking chances in Cypress, people are fast to notify us about them and we tend to fix things that have such a widespread consequence as "does not work with newest cypress". In such cases you can always use a bit older version, cypress is so advanced now that frequently is not an issue if you had to skip the newest version for a few weeks or even a few months
