### ISSUE TITLE
Showing "Given,When,Then" steps in output of the tests

### ISSUE THREAD

**Issue by volkanogretmen** [TheBrainFamily/cypress-cucumber-preprocessor#63]
Hi all,

I started using cypress-cucumber-preprocessor recently and I'm really fond of it! 

I have a question when executing the scenario's. I would like to see the actual "Given, When, Then" steps in the main output of the tests. It now shows the scenario titles in the output (also in the terminal) and the steps are somewhat hidden inside the actual step behind a log-command. Is this normal behaviour or am I missing something?

![image](https://user-images.githubusercontent.com/25029377/42086392-3680cb84-7b93-11e8-9714-037932c740a6.png)

_Note that I am using the "Given" step in the `Background` in the example above._

**Comment by lgandecki** [comment]
Hey, thanks!
:-)

Unfortunately, this is caused by:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/44

We don't have control over when cypress clears out things like local storage/sessions/cookies , having all steps treated as a separate scenario (to show nicely in the cypress UI) was causing cypress to reset the state between them, which was a no-go. 
Once cypress allows for changing the way it behaves (which is coming, supposedly), we will be able to revert that change

**Comment by slavede** [comment]
So is this feature now released with the latest version? If so, how can I see this report?
