### ISSUE TITLE
After scenario commands

### ISSUE THREAD

**Issue by Panetes** [TheBrainFamily/cypress-cucumber-preprocessor#86]
Hello there,

I'm enjoying your cucumber pre-processor so far but there's one thing I would really love to be able to do. Is it possible to add an after command that gets executed at the end of every scenario (whether the scenario passes or not)? 

This would be extremely useful to keep the application data clean if a scenario fails for whatever reason.  I know you can do this with Cypress, just don't know if it is possible to do it with the gherkin scenarios. 

Many thanks in advance.

**Comment by AlfaCoder** [comment]
+1

**Comment by stefanweck** [comment]
Before and after scenario commands would be really useful! But it feels like this repository isn't actively maintained.

**Comment by lgandecki** [comment]
To be an open source maintainer - this package has had 6 releases since December last year, the userbase almost doubled from ~7k to 13k installations a week during that time, last change in the repo 4 days ago, but no, "not actively maintained" :-)

Unfortunately, we are doing this for free, and if a feature is not necessary to our business, and not trivial to implement, we won't be able to do everything. Guys, we are more than happy to take PRs though! If you need something - code it :) 

Btw, this is most probably possible, as beforeEach and afterEach , if you layout your tests using the default mode:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#cypress-cucumber-preprocessor-style-recommended

take a look here for an example:

https://github.com/TheBrainFamily/cypress-cucumber-example/tree/master/cypress/integration/news/Google

**Comment by lgandecki** [comment]
We now have cucumber style After hooks
