### ISSUE TITLE
The step definitions are not detected from package.json

### ISSUE THREAD

**Issue by prsdcse** [TheBrainFamily/cypress-cucumber-preprocessor#89]
I have done all the configuration mentioned in the readme.

in plugin/index.js
`const cucumber = require('cypress-cucumber-preprocessor').default;
module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
};`

in package.json
`"cypress-cucumber-preprocessor": {
    "step_definitions": "./cypress/support/step_definitions"
  }`

When i run the test i see this error. 

> Error: Step implementation missing for: Goto google page

>

**Comment by lgandecki** [comment]
Thanks for reporting..
Although I think we will need a repro here, as you can see this repository actually uses the plugin to test itself, so we know it works - at least in the most basic way. :-)

Two things:

a) Are you on windows?
b) Can you try "cypress/support/..." instead of "./cypress/support/..."?

**Comment by lgandecki** [comment]
Closing this because there is no way to reproduce, and this is basic functionality. 
Please reopen with a repro/after answering the a/b points above. 

Thanks!

**Comment by avikhazra** [comment]
I m using cypress/support/... in windows 10 and same problem faced. same config I am also using. the same issue faced
@lgandecki please help me on this

**Comment by gero0413** [comment]
Yo también estoy presentando el mismo problema
