### ISSUE TITLE
eslint plugin

### ISSUE THREAD

**Issue by fcurella** [TheBrainFamily/cypress-cucumber-preprocessor#9]
I think we should create a `eslint-plugin-cucumber` that adds `given`, `when` and `then` to the environment globals (see https://eslint.org/docs/developer-guide/working-with-plugins#environments-in-plugins), so we don't need to add `/* global given, when, then */` to every step definition file in order to silence the linter.

I don't know if you'd rather create a separate repo, or host both packages in this one. Either way, if you can get it set up I could work on the code.

**Comment by fcurella** [comment]
Note that there's already a module called [`eslint-plugin-cucumber`](https://www.npmjs.com/package/eslint-plugin-cucumber) on npm, but it doesn't provide any globals.

**Comment by lgandecki** [comment]
Hmm, for that reason (and because I don't really like globals) I "import" the given when then like so:

const { when, then } = require("cypress-cucumber-preprocessor"); 

You could add globals to your eslint config, but I'm guessing you don't like that solution neither?

Eslint plugin is possible.. I think it should probably be more around the lines of eslint-plugin-cypress-cucumber , because it's not really specific to cucumber itself

**Comment by fcurella** [comment]
Somehow I  missed you could add specific globals directly into the eslintrc. I’ll close this issue.

**Comment by leegee** [comment]
Can `cy` be imported. 

Love the library on my first day, but for the ugly globals apparently enforced on us.

**Comment by lgandecki** [comment]
@leegee I'm not sure I understand.. Do you want to import cy instead of using it using the one attached to the global context (window)? I would rather have that too - but it's not really up to us, you would have to ask on https://github.com/cypress-io/cypress - although I doubt they would be willing to do so since mocha already puts a lot of globals for you (describe, test, it, etc).

**Comment by leegee** [comment]
Understood. Thanks!
