### ISSUE TITLE
Having Multiple Backgrounds in a single Feature File is throwing error

### ISSUE THREAD

**Issue by darasandeep91** [TheBrainFamily/cypress-cucumber-preprocessor#93]
I have a feature File and I have places multiple back grounds for different scenario in a single feature file like this 

as there is no support for hooks in Cypress cucumber pre processsor  

Feature: To test Login 

  Background:
    Setting up app for the below scenario 1

  Scenario: To Check if SVG Icon is present in offer status for an Active offer
  GWT statements

  Background:
    Setting up app for the below scenario 2
  Scenario: To check if the plans and services page shows Pending status for the offer in pending state
  GWT statements 

but Cypress is throwing a error 

![image](https://user-images.githubusercontent.com/16938840/44634224-6e744880-a95c-11e8-946f-88aae2900a59.png)

Where am i going wrong ?
how to deal with scenario level dependencies ?

**Comment by sabin-bhattarai-cko** [comment]
Any solution to this?

**Comment by OleksiiSerdiuk** [comment]
Have anyone found any options for this case?

**Comment by badeball** [comment]
@OleksiiSerdiuk, questions here don't get a lot of visibility and you will probably have better luck by explaining your particular use-case, because the original question is somewhat ambiguous.

Multiple backgrounds aren't supported. However you can group scenarios with the `Rule` keyword and every `Rule` can have its own `Background`.

> as there is no support for hooks in Cypress cucumber pre processsor

I can't recall the feature set at the time this issue was opened, but hooks are certainly supported now.
